# Slack RSS Feed Configuration
# Format:
# slack_channel: The Slack channel where updates will be posted (including #)
# feeds: List of RSS feed URLs to monitor for that channel

channels:
  - slack_channel: tech-blog-alerts
    feeds:
      - https://antirez.com/rss
      - https://go.dev/blog/feed.atom
      - https://michael.stapelberg.ch/feed.xml
      - https://tailscale.com/blog/index.xml
