name: RSS Feed Check

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'
  # Allow manual triggering from the GitHub web portal
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-feeds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build application
        run: go build -o rss-feed-manager ./cmd/main.go
      
      - name: Run RSS feed manager
        run: ./rss-feed-manager
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
      - name: Pull latest changes from remote
        run: |
          git fetch origin
          git pull origin main --rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update feed state [skip ci]
          file_pattern: state.json