name: RSS Feed Check

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'
  
  # Allow manual triggering from the GitHub web portal
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-feeds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch all history for proper state tracking
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build application
        run: go build -o rss-feed-manager ./cmd/main.go
      
      - name: Run RSS feed manager
        run: ./rss-feed-manager
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
      - name: Commit and push changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add state.json
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update feed state [skip ci]"
            git push
          fi
