name: RSS Feed Check

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'

permissions:
  contents: write

jobs:
  check-feeds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build application
        run: go build -o rss-feed-manager ./cmd/main.go
      
      - name: Run RSS feed manager
        run: ./rss-feed-manager
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      
      - name: Commit state changes
        if: success()
        run: |
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add state.json
            git diff --quiet && git diff --staged --quiet || git commit -m 'Update feed state'
            git push 